//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCenterApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rows
    {
        public int Id { get; set; }
        public int HeaderId { get; set; }
        public string ArticleName { get; set; }
        public decimal Quantity { get; set; }
        public decimal NetPrice { get; set; }
        public decimal GrossPrice { get; set; }
    
        public virtual Headers Headers { get; set; }
    }
}
